class Key:
    COVER_IMAGES = "cover_images"
    STORY_MAP = "story_map"
    STORY_NAME = "story_name"
    CHAPTER_NAME = "chapter_name"
    COVER_IMAGE_SELECT = "cover_image_select"
    ASPECT_RATIO = "aspect_ratio"
    ASPECT_RATIO_MAP = "aspect_ratio_map"
    STORY_PREMISE = "story_premise"
    STORY_CHAPTER_COUNT = "story_chapter_count"
    SCENE_IMAGES_STRUCTURE_SELECT = "scene_images_structure_select"
    VALIDATE_ASSET = "validate_asset"
    IMAGE_STYLE = "image_style"
    VS_FRAME_RATE = "video_setting_frame_rate"
    AS_BG_MUSIC_VOLUME_FACTOR = "audio_setting_bg_music_volume_factor"
    IS_IMAGE_STYLE = "image_setting_image_style"
    SS_CHAPTER_COUNT = "story_setting_chapter_count"
    SETTINGS = "settings"


class Constants:
    ALL = "All"
    COVER_IMAGES = "Cover Images"
    GENERATE_STORY = "Generate Story"
    INSPECT_STORY = "Inspect Story"
    SCENE_IMAGES = "Scene Images"
    BG_MUSIC = "Background Music"
    NARRATION = "Narration"
    VALIDATE_ASSETS = "Validate Assets"
